/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shareit;

import java.awt.Color;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anshal
 */
public class MV_MainPanel extends javax.swing.JFrame {
public static ServerSocket mobile_server_socket;
public static Socket mobile_socket;
public static boolean stable=false;
    /**
     * Creates new form MV_MainPanel
     */
    public MV_MainPanel() {
      
        initComponents();
        
    }
    public void dest(){
   this.dispose();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        host = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(324, 487));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        host.setBackground(new java.awt.Color(218, 116, 85));
        host.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 255));
        host.setText("Start Server");
        host.setMaximumSize(new java.awt.Dimension(145, 39));
        host.setMinimumSize(new java.awt.Dimension(145, 39));
        host.setPreferredSize(new java.awt.Dimension(145, 39));
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });
        getContentPane().add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 247, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/logo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 82));

        jLabel2.setForeground(new java.awt.Color(0, 100, 0));
        jLabel2.setText("Status : Server not Initiated");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 203, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/bg2.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
        MakeConnection mc=new MakeConnection();
        mc.start();
        CheckConnection cc=new CheckConnection();
        cc.start();
        
        
    }//GEN-LAST:event_hostActionPerformed
  
    public class CheckConnection extends Thread{
        public void run()
        {
            while(stable==false)
            {
                try {
                    sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MV_MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            MV_SharePanel mvs=new MV_SharePanel();
            mvs.getContentPane().setBackground( new Color(148, 188, 143) );
            mvs.setVisible(true);
            dest();
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton host;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
