/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shareit;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static shareit.MV_MainPanel.mobile_socket;

/**
 *
 * @author anshal
 */
public class MV_SharePanel extends javax.swing.JFrame {
    public static String File_path;
    public static OutputStream mos;
    public static InputStream mis;
    public static DataOutputStream mdos;
    public static DataInputStream mdis;
    /**
     * Creates new form MV_SharePanel
     */
    public MV_SharePanel() {
        try {
            initComponents();
            CheckConnectionStatus ccs=new CheckConnectionStatus();
            ccs.start();
            mos=mobile_socket.getOutputStream();
            mis=mobile_socket.getInputStream();
            mdos=new DataOutputStream(mobile_socket.getOutputStream());
            mdis=new DataInputStream(mobile_socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(MV_SharePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Send = new javax.swing.JButton();
        UrlField = new javax.swing.JTextField();
        Receive = new javax.swing.JButton();
        choose_file2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        share_status = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Send.setBackground(new java.awt.Color(84, 139, 84));
        Send.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Send.setForeground(new java.awt.Color(255, 255, 255));
        Send.setText("Send");
        Send.setMaximumSize(new java.awt.Dimension(145, 39));
        Send.setMinimumSize(new java.awt.Dimension(145, 39));
        Send.setPreferredSize(new java.awt.Dimension(145, 39));
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        getContentPane().add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, 284, 41));

        UrlField.setEditable(false);
        UrlField.setBackground(new java.awt.Color(189, 252, 201));
        getContentPane().add(UrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 284, -1));

        Receive.setBackground(new java.awt.Color(84, 139, 84));
        Receive.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Receive.setForeground(new java.awt.Color(255, 255, 255));
        Receive.setText("Receive");
        Receive.setMaximumSize(new java.awt.Dimension(145, 39));
        Receive.setMinimumSize(new java.awt.Dimension(145, 39));
        Receive.setPreferredSize(new java.awt.Dimension(145, 39));
        Receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveActionPerformed(evt);
            }
        });
        getContentPane().add(Receive, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 333, 284, 41));

        choose_file2.setBackground(new java.awt.Color(106, 169, 202));
        choose_file2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        choose_file2.setForeground(new java.awt.Color(255, 255, 255));
        choose_file2.setText("Choose File");
        choose_file2.setMaximumSize(new java.awt.Dimension(145, 39));
        choose_file2.setMinimumSize(new java.awt.Dimension(145, 39));
        choose_file2.setPreferredSize(new java.awt.Dimension(145, 39));
        choose_file2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_file2ActionPerformed(evt);
            }
        });
        getContentPane().add(choose_file2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 227, 284, 41));

        jProgressBar1.setBackground(new java.awt.Color(189, 252, 201));
        jProgressBar1.setForeground(new java.awt.Color(0, 100, 0));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, 284, 22));

        share_status.setForeground(new java.awt.Color(0, 100, 0));
        share_status.setText("Status : None");
        getContentPane().add(share_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 147, 142, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/pp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 18, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/bg2.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -3, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
       MV_Send_Thread mvst=new MV_Send_Thread();
       mvst.start();
    }//GEN-LAST:event_SendActionPerformed

    private void ReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveActionPerformed
        // TODO add your handling code here:
        MV_Receive_Thread mvrt=new MV_Receive_Thread();
        mvrt.start();
    }//GEN-LAST:event_ReceiveActionPerformed

    private void choose_file2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_file2ActionPerformed
        // TODO add your handling code here:
         Choose_thread ct=new Choose_thread();
        ct.start();
    }//GEN-LAST:event_choose_file2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MV_SharePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MV_SharePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MV_SharePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MV_SharePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MV_SharePanel().setVisible(true);
            }
        });
    }
    
    public class Choose_thread extends Thread{
        public void run(){
             JFileChooser jfc=new JFileChooser();
       
        jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result=jfc.showOpenDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File file=jfc.getSelectedFile();
             File_path=file.getAbsolutePath();
           UrlField.setText(File_path);
            
            
        }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Receive;
    private javax.swing.JButton Send;
    private javax.swing.JTextField UrlField;
    private javax.swing.JButton choose_file2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel share_status;
    // End of variables declaration//GEN-END:variables
}
