/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shareit;

//import com.sun.org.apache.xml.internal.resolver.helpers.PublicId;
import java.awt.Color;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import static java.lang.Math.ceil;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.DateFormat;
import java.util.Date;
import static java.util.Optional.empty;
import static java.util.OptionalDouble.empty;
import static java.util.OptionalLong.empty;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.util.stream.DoubleStream.empty;
import javax.net.ssl.SSLServerSocket;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Anshal Dwivedi
 */
public class Share_Panel extends javax.swing.JFrame {
public String file_path=null;
    /**
     * Creates new form Share_Panel
     */File history;
     FileOutputStream his_fos;
     BufferedWriter b;
    public Share_Panel() throws IOException {
        initComponents();
        Ip_Field.setText("");
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        Choose_file = new javax.swing.JButton();
        Send_file = new javax.swing.JButton();
        Recieve_file = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UrlPanel = new javax.swing.JTextField();
        ShareStatus = new javax.swing.JLabel();
        Ip_Field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Progress = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        Switch_To_phone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShareLite");
        setBackground(new java.awt.Color(171, 130, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Choose_file.setBackground(new java.awt.Color(102, 169, 202));
        Choose_file.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Choose_file.setForeground(new java.awt.Color(255, 255, 255));
        Choose_file.setText("Choose File");
        Choose_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_fileActionPerformed(evt);
            }
        });
        getContentPane().add(Choose_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 307, 290, 41));

        Send_file.setBackground(new java.awt.Color(228, 116, 25));
        Send_file.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Send_file.setForeground(new java.awt.Color(255, 255, 255));
        Send_file.setText("Send");
        Send_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_fileActionPerformed(evt);
            }
        });
        getContentPane().add(Send_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 354, 290, 41));

        Recieve_file.setBackground(new java.awt.Color(45, 172, 96));
        Recieve_file.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Recieve_file.setForeground(new java.awt.Color(255, 255, 255));
        Recieve_file.setText("Recieve");
        Recieve_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recieve_fileActionPerformed(evt);
            }
        });
        getContentPane().add(Recieve_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 401, 290, 41));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        UrlPanel.setEditable(false);
        UrlPanel.setBackground(new java.awt.Color(255, 255, 255));
        UrlPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlPanelActionPerformed(evt);
            }
        });
        getContentPane().add(UrlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 267, 290, 29));

        ShareStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ShareStatus.setForeground(new java.awt.Color(0, 100, 0));
        ShareStatus.setText("Status : None");
        getContentPane().add(ShareStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 240, 193, -1));

        Ip_Field.setBackground(new java.awt.Color(255, 255, 255));
        Ip_Field.setText(" ");
        Ip_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ip_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Ip_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 199, 290, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 100, 0));
        jLabel3.setText("Reciever's IP:-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 172, -1, -1));

        Progress.setBackground(new java.awt.Color(255, 255, 255));
        Progress.setForeground(new java.awt.Color(0, 100, 0));
        Progress.setStringPainted(true);
        getContentPane().add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, 290, 22));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/logo2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 158, 120));

        Switch_To_phone.setBackground(new java.awt.Color(144, 180, 235));
        Switch_To_phone.setForeground(new java.awt.Color(255, 255, 255));
        Switch_To_phone.setText("Android Mode");
        Switch_To_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Switch_To_phoneActionPerformed(evt);
            }
        });
        getContentPane().add(Switch_To_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shareit/bg2.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 1, 320, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Choose_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_fileActionPerformed
        // TODO add your handling code here:
        Progress.setValue(0);
       Choose_thread ct=new Choose_thread();
       ct.start();
       
    }//GEN-LAST:event_Choose_fileActionPerformed

    private void Send_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_fileActionPerformed
        // TODO add your handling code here:
        String rec_ip=Ip_Field.getText();
 //      
        if(rec_ip.equals(""))
        {
            System.out.println("bhai ip to daal");
            JOptionPane jo=new JOptionPane("ReciverIp is empty", 1);
        }
        else
        {
            Send_Thread st=new Send_Thread(file_path,rec_ip);
             st.start();
        }
      
       
    }//GEN-LAST:event_Send_fileActionPerformed

    private void Recieve_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recieve_fileActionPerformed
    Rec_Thread rt=new Rec_Thread();
    rt.start();
    }//GEN-LAST:event_Recieve_fileActionPerformed

    private void Ip_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ip_FieldActionPerformed
   
    }//GEN-LAST:event_Ip_FieldActionPerformed

    private void UrlPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlPanelActionPerformed

    private void Switch_To_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Switch_To_phoneActionPerformed
        // TODO add your handling code here:
        MV_MainPanel mvp=new MV_MainPanel();
        mvp.getContentPane().setBackground( new Color(148, 188, 143) );
        mvp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Switch_To_phoneActionPerformed
    

    public class Choose_thread extends Thread{
        public void run(){
             JFileChooser jfc=new JFileChooser();
       
        jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result=jfc.showOpenDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File file=jfc.getSelectedFile();
             file_path=file.getAbsolutePath();
           UrlPanel.setText(file_path);
            
            
        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose_file;
    public javax.swing.JTextField Ip_Field;
    public static javax.swing.JProgressBar Progress;
    public static javax.swing.JButton Recieve_file;
    public static javax.swing.JButton Send_file;
    public static javax.swing.JLabel ShareStatus;
    private javax.swing.JButton Switch_To_phone;
    private javax.swing.JTextField UrlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
